### ISSUE TITLE
Error in  function authenticate

### ISSUE THREAD

**Issue by 909402317** [garbetjie/wechat-php#12]
This part:
// Cached access token is still valid. Return it.
        if ($cached instanceof AccessToken && $cached->valid()) {
            return $cached;
        }

Should be:

// Cached access token is still valid. Return it.
        if ($cached instanceof AccessToken && $cached->valid()) {
			return $this->client->withAccessToken($cached);
        }

**Comment by garbetjie** [comment]
You're welcome to make a pull request, but this package is no longer maintained. It will be archived shortly.

**Comment by solverat** [comment]
@garbetjie may I ask why you want to archive this package? As far as I can see, this extension is the only "english based/documented" 😄  SDK so it would be cool if it stays alive. We also use this package in our [WeChat connector](https://github.com/dachcom-digital/pimcore-social-data-wechat-connector). 

Thanks for your feedback and also thank you for your contributions! 💪

**Comment by garbetjie** [comment]
@solverat I didn't realise this was still being used, considering how old and outdated it is. I won't archive it, because it seems like it might still be used.

However, I'm not actively working on WeChat anymore, so there aren't really going to be any updates coming from me.

I know it's not English, but have you investigated https://github.com/overtrue/wechat? It's got far more functionality that this SDK has, and is continually updated.
